-- Inventory Counts table
CREATE TABLE IF NOT EXISTS inventory_counts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    inventoryNumber VARCHAR(50) NOT NULL UNIQUE,
    inventoryDate DATE NOT NULL,
    branchId INT NULL,
    status ENUM('DRAFT', 'COMPLETED', 'APPROVED') NOT NULL DEFAULT 'DRAFT',
    notes TEXT NULL,
    createdBy INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (branchId) REFERENCES branches(id) ON DELETE SET NULL,
    FOREIGN KEY (createdBy) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Inventory Count Items table
CREATE TABLE IF NOT EXISTS inventory_count_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    inventoryCountId INT NOT NULL,
    itemId INT NOT NULL,
    quantity DECIMAL(10, 4) NOT NULL,
    unitId INT NOT NULL,
    cost DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    total DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (inventoryCountId) REFERENCES inventory_counts(id) ON DELETE CASCADE,
    FOREIGN KEY (itemId) REFERENCES items(id) ON DELETE RESTRICT,
    FOREIGN KEY (unitId) REFERENCES units(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
